"""Tetris, as much of it as a decision needs and no more.

Here to be a *use case* rather than a game: a loop where something looks at a state and picks one of a few dozen
moves, over and over. That shape is what this package is for and none of its other measurements have it -- RACE and
BoolQ ask about a document that somebody else wrote, while this asks about a state the previous decision produced, so a
bad decision is visible several moves later rather than immediately.

Deliberately the simplified game the literature compares agents on: a piece is dropped straight down into a chosen
column at a chosen rotation, with no sliding underneath an overhang. That loses a real player's best moves and gains
the only thing a comparison needs, which is that every agent faces exactly the same set of choices.

No rendering, no timing, no levels, no scoring curve. Lines cleared and pieces placed are the whole outcome.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field

WIDTH = 10
HEIGHT = 20

#: The seven tetrominoes, each as the rotations it actually has -- four for L, J and T, two for S, Z and I, one for O.
#: Written out rather than generated by rotating a matrix, because generating them produces duplicate rotations for the
#: symmetric pieces and then an agent's "choose a rotation" has options that do nothing.
PIECES: dict[str, list[list[tuple[int, int]]]] = {
    "I": [[(0, 0), (0, 1), (0, 2), (0, 3)], [(0, 0), (1, 0), (2, 0), (3, 0)]],
    "O": [[(0, 0), (0, 1), (1, 0), (1, 1)]],
    "T": [
        [(0, 0), (0, 1), (0, 2), (1, 1)],
        [(0, 1), (1, 0), (1, 1), (2, 1)],
        [(0, 1), (1, 0), (1, 1), (1, 2)],
        [(0, 0), (1, 0), (1, 1), (2, 0)],
    ],
    "S": [[(0, 1), (0, 2), (1, 0), (1, 1)], [(0, 0), (1, 0), (1, 1), (2, 1)]],
    "Z": [[(0, 0), (0, 1), (1, 1), (1, 2)], [(0, 1), (1, 0), (1, 1), (2, 0)]],
    "J": [
        [(0, 0), (1, 0), (1, 1), (1, 2)],
        [(0, 0), (0, 1), (1, 0), (2, 0)],
        [(0, 0), (0, 1), (0, 2), (1, 2)],
        [(0, 1), (1, 1), (2, 0), (2, 1)],
    ],
    "L": [
        [(0, 2), (1, 0), (1, 1), (1, 2)],
        [(0, 0), (1, 0), (2, 0), (2, 1)],
        [(0, 0), (0, 1), (0, 2), (1, 0)],
        [(0, 0), (0, 1), (1, 1), (2, 1)],
    ],
}

NAMES = tuple(PIECES)


@dataclass(frozen=True)
class Move:
    """One placement: which rotation, and which column its left edge sits in."""

    rotation: int
    column: int

    def describe(self, piece: str) -> str:
        """How a move is put to a model. One place, so the agent and anything reading a transcript agree."""
        turns = {0: "upright", 1: "turned once", 2: "turned twice", 3: "turned three times"}
        return f"{piece} {turns.get(self.rotation, f'rotation {self.rotation}')}, left edge in column {self.column}"


@dataclass
class Board:
    """Filled cells, row 0 at the top. A list of lists rather than a bitmask: this is read by people more than by
    hot loops, and the agents spend their time in a 35 GiB model rather than here."""

    rows: list[list[bool]] = field(default_factory=lambda: [[False] * WIDTH for _ in range(HEIGHT)])

    def copy(self) -> Board:
        return Board([row[:] for row in self.rows])

    def heights(self) -> list[int]:
        """Filled height of each column, counting from the floor."""
        out = []
        for x in range(WIDTH):
            height = 0
            for y in range(HEIGHT):
                if self.rows[y][x]:
                    height = HEIGHT - y
                    break
            out.append(height)
        return out

    def holes(self) -> int:
        """Empty cells with something filled above them. The quantity a Tetris position is mostly judged by, because
        an empty cell under a filled one cannot be filled without clearing the row above it first."""
        total = 0
        for x in range(WIDTH):
            seen = False
            for y in range(HEIGHT):
                if self.rows[y][x]:
                    seen = True
                elif seen:
                    total += 1
        return total

    def render(self) -> str:
        """The board as text, which is what a model is given. Column numbers on top because every move names one, and a
        model asked to reason about column 7 with nothing to count along has to count the character positions itself."""
        header = "".join(str(x % 10) for x in range(WIDTH))
        lines = [f"  {header}", f"  {'-' * WIDTH}"]
        for y, row in enumerate(self.rows):
            lines.append(f"{y:2d}|" + "".join("#" if cell else "." for cell in row) + "|")
        lines.append(f"  {'-' * WIDTH}")
        lines.append("  " + header)
        return "\n".join(lines)


def cells(piece: str, move: Move) -> list[tuple[int, int]]:
    shape = PIECES[piece][move.rotation % len(PIECES[piece])]
    return [(dy, dx + move.column) for dy, dx in shape]


def legal_moves(piece: str) -> list[Move]:
    """Every rotation in every column it fits in. The same list for a given piece whatever the board holds, which is
    what lets one prompt describe the choices without recomputing them per state."""
    out = []
    for rotation, shape in enumerate(PIECES[piece]):
        span = max(dx for _, dx in shape) + 1
        out.extend(Move(rotation=rotation, column=column) for column in range(WIDTH - span + 1))
    return out


def landing_row(board: Board, piece: str, move: Move) -> int | None:
    """How far down the piece falls, or None if it cannot enter at all.

    A straight drop: the piece is lowered until one of its cells would overlap something or leave the floor. Returns the
    offset added to each cell's row.
    """
    shape = cells(piece, move)
    depth = max(dy for dy, _ in shape)
    if any(x < 0 or x >= WIDTH for _, x in shape):
        return None
    drop = None
    for offset in range(HEIGHT - depth):
        if any(board.rows[dy + offset][x] for dy, x in shape):
            break
        drop = offset
    return drop


def apply(board: Board, piece: str, move: Move) -> tuple[Board, int] | None:
    """The board after the placement and how many rows it cleared, or None if the placement does not fit."""
    drop = landing_row(board, piece, move)
    if drop is None:
        return None
    after = board.copy()
    for dy, x in cells(piece, move):
        after.rows[dy + drop][x] = True
    kept = [row for row in after.rows if not all(row)]
    cleared = HEIGHT - len(kept)
    after.rows = [[False] * WIDTH for _ in range(cleared)] + kept
    return after, cleared


def bag(seed: int, count: int) -> list[str]:
    """A seeded sequence of pieces, drawn seven at a time as the real game does.

    Seeded and shared: two agents are compared on the same pieces in the same order, so a difference is the agent's.
    Drawing uniformly at random instead would let one agent be handed four I pieces and call it skill.
    """
    rng = random.Random(seed)
    out: list[str] = []
    while len(out) < count:
        seven = list(NAMES)
        rng.shuffle(seven)
        out.extend(seven)
    return out[:count]


def draw(board: Board, cell: int = 24, margin: int = 28):
    """The board as an image, for the path that has a vision tower behind it.

    Here because rendering it as characters and concluding the model cannot see it left out the obvious alternative. A
    grid written in text loses the one thing that matters: tokenisation merges runs of dots into pieces whose boundaries
    differ from row to row, so nothing tells the model that the fifth character of one line is above the fifth character
    of the next. Image patches carry two-dimensional positions in this model's own position scheme; text carries one.

    Drawn plainly and large: filled cells as solid squares, a one-pixel grid so empty cells are countable, and the
    column numbers along the top because every move names a column.
    """
    from PIL import Image, ImageDraw

    width, height = WIDTH * cell + 2 * margin, HEIGHT * cell + 2 * margin
    image = Image.new("RGB", (width, height), "white")
    pen = ImageDraw.Draw(image)
    for x in range(WIDTH):
        pen.text((margin + x * cell + cell // 3, margin // 3), str(x), fill="black")
    for y in range(HEIGHT):
        pen.text((margin // 4, margin + y * cell + cell // 4), f"{y:2d}", fill="black")
    for y in range(HEIGHT):
        for x in range(WIDTH):
            box = (margin + x * cell, margin + y * cell, margin + (x + 1) * cell, margin + (y + 1) * cell)
            pen.rectangle(box, fill="black" if board.rows[y][x] else "white", outline="grey")
    return image
